# Generated by Django 2.0.6 on 2019-12-26 04:58

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=512)),
                ('email', models.EmailField(db_index=True, max_length=128, unique=True)),
                ('candidate_url', models.CharField(blank=True, default=None, max_length=1024)),
                ('mobile', models.BigIntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(5000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('address', models.CharField(default=None, max_length=1024)),
                ('min_ctc', models.FloatField(default=0.0)),
                ('max_ctc', models.FloatField(default=1000.0)),
                ('notice_days', models.IntegerField(default=60)),
                ('is_already_on_notice', models.BooleanField()),
                ('tech_skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=256)),
            ],
            options={
                'db_table': 'api_candidate',
            },
        ),
    ]
