# Generated by Django 2.0.6 on 2019-12-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_already_on_notice',
        ),
    ]
