# Generated by Django 2.0.6 on 2019-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate_File',
        ),
        migrations.AddField(
            model_name='candidate',
            name='Resume',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
