# Generated by Django 2.0.6 on 2019-12-29 12:14

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20191229_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Resume',
            field=models.FileField(upload_to=candidate.models.user_directory_path),
        ),
    ]
