# Generated by Django 2.0.6 on 2020-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20200122_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='certification',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
