# Generated by Django 2.0.6 on 2020-01-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_remove_candidate_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='master',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='master_per',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
