# Generated by Django 2.0.6 on 2020-06-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_auto_20200624_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='tech_skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
