# Generated by Django 2.0.6 on 2020-09-08 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTracker',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_status', models.CharField(choices=[('Pending', ' Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=256)),
                ('from_date', models.DateField()),
                ('applied_date', models.DateField(auto_now_add=True, null=True)),
                ('to_date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('total_leaves', models.IntegerField(default=30)),
                ('available_leaves', models.IntegerField(default=30, null=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_tracker',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Planned', 'PLANNED'), ('Emergancy', 'EMERGANCY'), ('Sick', 'SICK')], default='Planned', max_length=256)),
            ],
            options={
                'db_table': 'api_leave_type',
            },
        ),
        migrations.AddField(
            model_name='leavetracker',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_management.LeaveType'),
        ),
        migrations.AddField(
            model_name='leavetracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
