# Generated by Django 2.0.6 on 2020-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetracker',
            name='leave_status',
            field=models.CharField(choices=[('Pending', ' PENDING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED')], default='Pending', max_length=256),
        ),
    ]
