# Generated by Django 2.0.6 on 2020-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_auto_20200709_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetracker',
            name='available_leaves',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
