# Generated by Django 2.0.6 on 2020-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200630_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_company',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
