[
    {
        "id": "72c0154d-9f6c-47d0-a9c2-a039f07f2d06",
        "name": "asc",
        "email": "priya@gmail.com",
        "candidate_url": "sdfghj",
        "mobile": 96543210,
        "address": "asd",
        "min_ctc": 0.0,
        "max_ctc": 1000.0,
        "notice_days": 180,
        "tech_skills": "python,java",
        "location": "banglore",
        "status": "active",
        "Resume": "http://127.0.0.1:8000/media/user_resumes/Priya_Patil_Jul19_Resume.docx"
    },
    {
        "id": "741491c7-d3ed-48e1-a00e-03e181d8fbd1",
        "name": "Ragu",
        "email": "abc@gmail.com",
        "candidate_url": "aaaaaaaaaaaa",
        "mobile": 9988776655,
        "address": "ccccccc",
        "min_ctc": 0.0,
        "max_ctc": 1000.0,
        "notice_days": 150,
        "tech_skills": "python,java,.Net,js",
        "location": "banglore",
        "status": "active",
        "Resume": null
    },
    {
        "id": "a7bdbeb2-9cf6-4319-a618-c869b4a2b44e",
        "name": "Ram",
        "email": "abc123@gmail.com",
        "candidate_url": "aaaddddddd",
        "mobile": 9988776644,
        "address": "bbbbbbbbb",
        "min_ctc": 0.0,
        "max_ctc": 1000.0,
        "notice_days": 150,
        "tech_skills": "python,java,.Net",
        "location": "Dheli",
        "status": "active",
        "Resume": null
    },
    {
        "id": "1780ff9b-a471-4e63-80b3-677cb43f1bd8",
        "name": "aaa",
        "email": "dddd@gmail.com",
        "candidate_url": "cccccccccc",
        "mobile": 9988776622,
        "address": "bbbbbbbbb",
        "min_ctc": 0.0,
        "max_ctc": 1000.0,
        "notice_days": 150,
        "tech_skills": "python,java,.Net,react,",
        "location": "Pune",
        "status": "active",
        "Resume": null
    }
]