# Generated by Django 2.0.6 on 2019-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reporting_manager',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
