# Generated by Django 2.0.6 on 2020-02-25 14:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permissions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, choices=[('candidate_add', 'True'), ('candidate_edit', 'False'), ('candidate_read', 'False'), ('candidate_delete', 'False'), ('client_add', 'True'), ('client_edit', 'False'), ('client_read', 'False'), ('client_delete', 'False'), ('job_add', 'True'), ('job_edit', 'False'), ('job_read', 'False'), ('job_delete', 'False'), ('interview_add', 'True'), ('interview_edit', 'False'), ('interview_read', 'False'), ('interview_delete', 'False')], default='candidate_add', max_length=256, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='permissions',
        ),
    ]
