# Generated by Django 2.0.6 on 2020-02-25 15:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200225_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, choices=[('candidate_add', 'candidate_add'), ('candidate_edit', 'False'), ('candidate_read', 'False'), ('candidate_delete', 'False'), ('client_add', 'True'), ('client_edit', 'False'), ('client_read', 'False'), ('client_delete', 'False'), ('job_add', 'True'), ('job_edit', 'False'), ('job_read', 'False'), ('job_delete', 'False'), ('interview_add', 'True'), ('interview_edit', 'False'), ('interview_read', 'False'), ('interview_delete', 'False')], max_length=256, null=True),
        ),
    ]
