# Generated by Django 2.0.6 on 2020-06-16 17:58

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200509_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reporting_manager',
            new_name='anual_salary',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image_url',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='block_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_attempts_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marks',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='passing_year',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='resigned_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='work_loc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default=None, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(db_index=True, default=None, unique=True, validators=[django.core.validators.MinValueValidator(5000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
