# Generated by Django 2.0.6 on 2020-06-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200626_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
