# Generated by Django 2.0.6 on 2020-06-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200626_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='work_loc',
            new_name='work_location',
        ),
    ]
