# Generated by Django 2.0.6 on 2020-09-08 12:31

import candidate.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=512, null=True)),
                ('last_name', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.EmailField(db_index=True, max_length=128, unique=True)),
                ('candidate_url', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('mobile', models.BigIntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(5000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=6, null=True)),
                ('sslc_marks', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('puc_marks', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bachelor_degree', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bachelor_degree_course', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bachelor_degree_marks', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('master_degree', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('master_degree_course', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('master_degree_marks', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('tech_skills', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, max_length=100, null=True)),
                ('previous_company', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('work_experience', models.FloatField(blank=True, default=None, max_length=100, null=True)),
                ('current_ctc', models.FloatField(blank=True, default=0.0, null=True)),
                ('expected_ctc', models.FloatField(blank=True, default=1000.0, null=True)),
                ('notice_period', models.IntegerField(blank=True, default=60, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=candidate.models.user_directory_path)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=256)),
            ],
            options={
                'db_table': 'api_candidate',
            },
        ),
    ]
