# Generated by Django 2.0.6 on 2020-01-22 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20191229_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='max_ctc',
            new_name='expected_ctc',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='min_ctc',
            new_name='previous_ctc',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate_url',
            new_name='profile_link',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='Resume',
            new_name='resume',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
        migrations.AddField(
            model_name='candidate',
            name='certification',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree_per',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 29, 45, 336333, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='master',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 30, 28, 820817, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_per',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 30, 44, 991044, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='previous_company',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 30, 59, 13903, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='puc',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 31, 15, 639180, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='puc_per',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 31, 43, 123420, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='sslc',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 32, 3, 43574, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='sslc_per',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 32, 11, 774668, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_experience',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 32, 21, 813966, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_location',
            field=models.CharField(default=datetime.datetime(2020, 1, 22, 9, 32, 31, 498630, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
