# Generated by Django 2.0.6 on 2020-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20200122_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='degree',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='degree_per',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='master',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='master_per',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previous_company',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='puc',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='puc_per',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sslc',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sslc_per',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
