# Generated by Django 2.0.6 on 2020-01-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20200122_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='certification',
        ),
    ]
