# Generated by Django 2.0.6 on 2020-01-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20200123_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='certification',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.FloatField(default=None, max_length=100),
        ),
    ]
