# Generated by Django 2.0.6 on 2020-01-24 04:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_auto_20200124_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='work_location',
        ),
        migrations.AddField(
            model_name='candidate',
            name='prepared_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, max_length=100),
        ),
    ]
