# Generated by Django 2.0.6 on 2020-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_auto_20200124_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='degree',
            new_name='bachelor_degree',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='master',
            new_name='bachelor_degree_course',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='master_per',
            new_name='bachelor_degree_marks',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='profile_link',
            new_name='candidate_url',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='previous_ctc',
            new_name='current_ctc',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='notice_days',
            new_name='notice_period',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='prepared_location',
            new_name='prefered_location',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='degree_per',
            new_name='puc_marks',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='puc',
            new_name='sslc_marks',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='puc_per',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='sslc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='sslc_per',
        ),
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_degree',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_degree_course',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_degree_marks',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
