# Generated by Django 2.0.6 on 2020-06-23 13:33

import candidate.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_auto_20200618_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bachelor_degree',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='prefered_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previous_company',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='puc_marks',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, upload_to=candidate.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sslc_marks',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=256),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.FloatField(blank=True, default=None, max_length=100),
        ),
    ]
