# Generated by Django 2.0.6 on 2020-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_auto_20200624_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
