# Generated by Django 2.0.6 on 2020-09-08 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default=None, max_length=512, unique=True)),
                ('web_link', models.CharField(default=None, max_length=512)),
                ('ceo', models.CharField(blank=True, max_length=512, null=True)),
                ('founder', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('founded_on', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('email', models.CharField(max_length=512)),
                ('mobile', models.CharField(max_length=512)),
                ('revenue', models.CharField(blank=True, max_length=512, null=True)),
                ('latest_funding', models.CharField(blank=True, max_length=512, null=True)),
                ('headquarter', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('profile_desc', models.CharField(blank=True, max_length=1024, null=True)),
                ('aggrement_doc', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('on_hold', 'ON_HOLD'), ('expiried', 'EXPIRED')], default='active', max_length=256, null=True)),
                ('industry', models.CharField(choices=[('Finance', 'Finance'), ('Resources', 'Resources'), ('Products', 'Products'), ('Health and public', 'Health and public')], default='Products', max_length=200, null=True)),
                ('category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Other', 'Other')], default='Private', max_length=200, null=True)),
            ],
            options={
                'db_table': 'api_client',
            },
        ),
    ]
