# Generated by Django 2.0.6 on 2020-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('Public', 'PUBLIC'), ('Private', 'PRIVATE'), ('Other', 'OTHER')], default='Private', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='founded_on',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='founder',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(choices=[('Finance', 'FINANCE'), ('Resources', 'RESOURCES'), ('Products', 'PRODUCTS'), ('Health and public', 'HEALTH AND PUBLIC')], default='Products', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='web_link',
            field=models.CharField(max_length=512),
        ),
    ]
