# Generated by Django 2.0.6 on 2020-06-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20200623_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='web_link',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
