# Generated by Django 2.0.6 on 2020-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20200624_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='aggrement_doc',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ceo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='founded_on',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='founder',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='headquarter',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='latest_funding',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='revenue',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('on_hold', 'ON_HOLD'), ('expiried', 'EXPIRED')], default='active', max_length=256, null=True),
        ),
    ]
