# Generated by Django 2.0.6 on 2020-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20200624_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_ctc',
            field=models.FloatField(blank=True, default=1000.0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_exp',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_notice_period',
            field=models.IntegerField(blank=True, default=90, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_ctc',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_exp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_notice_period',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='percentage_criteria',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
