# Generated by Django 2.0.6 on 2020-09-08 12:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(default=None, max_length=512)),
                ('jd_url', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('tech_skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('job_location', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('job_type', models.CharField(choices=[('permanent', 'PERMANENT'), ('contract', 'CONTRACT'), ('part_time', 'PART_TIME')], default='permanent', max_length=256)),
                ('min_exp', models.IntegerField(blank=True, default=0, null=True)),
                ('max_exp', models.IntegerField(blank=True, default=60, null=True)),
                ('min_notice_period', models.IntegerField(blank=True, default=60, null=True)),
                ('max_notice_period', models.IntegerField(blank=True, default=90, null=True)),
                ('min_ctc', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_ctc', models.FloatField(blank=True, default=1000.0, null=True)),
                ('qualification', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('percentage_criteria', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('on_hold', 'ON_HOLD'), ('expiried', 'EXPIRED')], default='active', max_length=256)),
                ('jd_extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='clients.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
