# Generated by Django 2.0.6 on 2020-06-19 13:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=512)),
                ('web_link', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('ceo', models.CharField(default=None, max_length=512)),
                ('founder', models.CharField(default=None, max_length=512)),
                ('founded_on', models.CharField(default=None, max_length=512)),
                ('email', models.CharField(default=None, max_length=512)),
                ('mobile', models.CharField(default=None, max_length=512)),
                ('revenue', models.CharField(default=None, max_length=512)),
                ('latest_funding', models.CharField(default=None, max_length=512)),
                ('headquarter', models.CharField(default=None, max_length=512)),
                ('address', models.CharField(default=None, max_length=1024)),
                ('profile_desc', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('aggrement_doc', models.CharField(default=None, max_length=1024)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('on_hold', 'ON_HOLD'), ('expiried', 'EXPIRED')], default='active', max_length=256)),
            ],
            options={
                'db_table': 'api_client',
            },
        ),
        migrations.CreateModel(
            name='Clientcategory',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_category', models.CharField(choices=[('PB', 'Public'), ('PR', 'Private'), ('OT', 'Other')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clientindustry',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_industry', models.CharField(choices=[('FN', 'Finance'), ('RS', 'Resources'), ('PD', 'Products'), ('HP', 'Health and public')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(default=None, max_length=512)),
                ('jd_url', models.CharField(blank=True, default=None, max_length=1024)),
                ('tech_skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('job_location', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('job_type', models.CharField(choices=[('permanent', 'PERMANENT'), ('contract', 'CONTRACT'), ('part_time', 'PART_TIME')], default='permanent', max_length=256)),
                ('min_exp', models.IntegerField(default=0)),
                ('max_exp', models.IntegerField(default=60)),
                ('min_notice_period', models.IntegerField(default=60)),
                ('max_notice_period', models.IntegerField(default=90)),
                ('min_ctc', models.FloatField(default=0.0)),
                ('max_ctc', models.FloatField(default=1000.0)),
                ('qualification', models.CharField(blank=True, default=None, max_length=100)),
                ('percentage_criteria', models.CharField(blank=True, default=None, max_length=100)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('on_hold', 'ON_HOLD'), ('expiried', 'EXPIRED')], default='active', max_length=256)),
                ('jd_extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='clients.Client')),
            ],
            options={
                'db_table': 'api_job',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='Clientcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='clients.Clientcategory'),
        ),
        migrations.AddField(
            model_name='client',
            name='clientindustry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='industry', to='clients.Clientindustry'),
        ),
    ]
