# Generated by Django 2.0.6 on 2020-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_location',
            new_name='location',
        ),
    ]
