# Generated by Django 2.0.6 on 2020-06-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200619_2328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='api_jobs',
        ),
    ]
