# Generated by Django 2.0.6 on 2020-06-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200619_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Clientcategory',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientindustry',
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('PB', 'Public'), ('PR', 'Private'), ('OT', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(choices=[('FN', 'Finance'), ('RS', 'Resources'), ('PD', 'Products'), ('HP', 'Health and public')], max_length=200, null=True),
        ),
    ]
