# Generated by Django 2.0.6 on 2020-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200623_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='aggrement_doc',
            field=models.CharField(blank=True, default=None, max_length=1024),
        ),
    ]
