# Generated by Django 2.0.6 on 2020-06-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20200624_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('PB', 'Public'), ('PR', 'Private'), ('OT', 'Other')], default='PR', max_length=200, null=True),
        ),
    ]
