# Generated by Django 2.0.6 on 2020-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20200624_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=512, unique=True),
        ),
    ]
