# Generated by Django 2.0.6 on 2020-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20200625_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jd_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
