# Generated by Django 2.0.6 on 2020-07-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20200626_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientcategory',
        ),
        migrations.DeleteModel(
            name='Clientindustry',
        ),
    ]
