# Generated by Django 2.0.6 on 2020-07-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20200707_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_status',
            field=models.ForeignKey(blank=True, default='TS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterviewStatus', to='interview.InterviewStatus'),
        ),
    ]
