# Generated by Django 2.0.6 on 2020-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_auto_20200708_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetracker',
            name='applied_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
