# Generated by Django 2.0.6 on 2020-07-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_auto_20200709_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetracker',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
