# Generated by Django 2.0.6 on 2020-09-08 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('candidate', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(default=None, max_length=256)),
                ('candidate', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Candidates', to='candidate.Candidate')),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.Client')),
            ],
            options={
                'db_table': 'api_interview',
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_round', models.CharField(choices=[('FR', 'Online round'), ('SR', 'Technical round'), ('TR', 'HR round')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewStatus',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FS', 'Processing'), ('SS', 'Completed'), ('TS', 'Sheduled')], default='FS', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_round',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterviewRounds', to='interview.InterviewRound'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterviewStatus', to='interview.InterviewStatus'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Jobs', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
