# Generated by Django 2.0.6 on 2020-09-09 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Candidates', to='candidate.Candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InterviewRounds', to='interview.InterviewRound'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Jobs', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewround',
            name='interview_round',
            field=models.CharField(choices=[('Online round', 'ONLINE ROUND'), ('Technical round', 'TECHNICAL ROUND'), ('HR round', 'HR ROUND')], max_length=200),
        ),
        migrations.AlterField(
            model_name='interviewstatus',
            name='status',
            field=models.CharField(choices=[('Processing', 'PROCESSING'), ('Completed', 'COMPLETED'), ('Sheduled', 'SHEDULED')], default='Processing', max_length=256),
        ),
    ]
